default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: localhost
  database: stories
  username: admin

test:
  <<: *default
  database: stories

production:
  <<: *default

