# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93ee19521802e8e027c46c1fc0e2572a5a0ef5468738b38d2798bde2d95fb855fddc90c8a1e3fd80eddeba177dac2e30f72b76b24c8db4d0e8bddacc6cf8a8cb

test:
  secret_key_base: a84c819d1a2e878c8c1bf18b7b63ff6ef0ec45be1f34d494c84e56ba1d7e464c6bf58ebf5c3fcfa611a8aac8579609a8cba1f968c6973e3a8366e1cc5ec6c659

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
